### ISSUE TITLE
Local Development

### ISSUE THREAD

**Issue by digitaldesigndj** [FlexiDB/PublicFlexiDBServer#1]
I just wanted to try this software out. I need to make a REST API, and I remembered y'all from WordCamp Phoenix '16.

<img width="608" alt="screenshot 2017-11-10 16 43 28" src="https://user-images.githubusercontent.com/539320/32683165-6f4f11ea-c636-11e7-84ec-7cf310931cec.png">

Sure, I probably _should_ have a password on my DB, but I'm lazy, and the url looks fine to me. Just a small gripe. I can hack around it. I got it installed, logged in, the admin works fine until:

<img width="570" alt="screenshot 2017-11-10 16 49 06" src="https://user-images.githubusercontent.com/539320/32683246-22aeca50-c637-11e7-9f69-31771dbfa59f.png">

I have to go digging in the php to figure out why the routes are broken!

Darn, I downloaded this cause I wanted to be *lazy* and still develop a REST API.

It looks like a great product, and I'm here complaining about something free. 🤔

**Comment by digitaldesigndj** [comment]
I think this is more about the lack of a readme.md than an actual issue with the software.

**Comment by flexidbgit** [comment]
Hi,

I’m based in the UK and with the time difference it’s almost midnight here.
Can I send you an email on Monday with info?

Can you also let me know what sort of REST API you are looking to create?
What’s the project? Happy to help out.


Cheers,

Rich

**Comment by digitaldesigndj** [comment]
Certainly, no rush here, thanks for responding! 😄 

My client is https://www.iifym.com. We need some basic eCommerce stuff. We also track the fitness calculator results and provide meal plans for clients. Products, Customers, Foods, Macronutrients, and that pretty much covers it.
